
package vista;
import java.sql.Connection;//conexion a BD
import java.sql.DriverManager;//driver de conexion
import java.sql.ResultSet;//resultado final de datos
import java.sql.ResultSetMetaData;//resultado de metadatos
import java.sql.SQLException;//Tratamiento de Errros de BD SQL
import java.sql.Statement;//Generador de sentencias SQL    DDL,DML,DCL
import java.text.SimpleDateFormat;//Formatear datos
import java.util.Date;//fecha de sistema
import javax.swing.ImageIcon;//Tratamiento de imagenes
import javax.swing.JOptionPane;//ventanas emergentes
import javax.swing.table.DefaultTableModel;//tabla de datos
import modelo.Rutinas;


public class RegistroRutina extends javax.swing.JFrame {

    
        //objetos de conexion
        public Connection cn;
        public Statement stmt;
        public ResultSet rs;
        
        //clase Rutina genera objRutina para tratamiento de ifnormacion
        
        Rutinas objRutina = new Rutinas();
        
        
    public RegistroRutina() {
        initComponents();
        setLocationRelativeTo(null);//centra ventana
    }
    
     public void conectarBase(){//Inicia metodo
    try{ //inicia try
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost/bdisGym","uisGym","udl12345GYM");
            JOptionPane.showMessageDialog(null, "Conexion a BD OK\n\nMARQS'GYM");
            stmt=cn.createStatement();//genera sentencias sobre objetos de base de datos
    }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error de base de datos 1: \n"+ ex);
    }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error de base de datos 2:"+ e);
     }
    }//termina metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipañ = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        bnRegresarMenu = new javax.swing.JButton();
        panSecundarioRutina = new javax.swing.JPanel();
        lblIdRutina = new javax.swing.JLabel();
        lblNumeroRutina = new javax.swing.JLabel();
        lblNombreRutina = new javax.swing.JLabel();
        lblTipoRutina = new javax.swing.JLabel();
        lblRepeticionesRutina = new javax.swing.JLabel();
        txtIdRutina = new javax.swing.JTextField();
        txtNumeroRutina = new javax.swing.JTextField();
        txtNombreRutina = new javax.swing.JTextField();
        txtTipoRutina = new javax.swing.JTextField();
        txtRepeticionesRutina = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblSeleccionaRutina = new javax.swing.JLabel();
        cboPartesCuerpo = new javax.swing.JComboBox<>();
        lblResultado = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipañ.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Registrar nueva Rutina");

        bnRegresarMenu.setBackground(new java.awt.Color(255, 204, 204));
        bnRegresarMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnRegresarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        bnRegresarMenu.setText("Regresar al Menu");
        bnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnRegresarMenuActionPerformed(evt);
            }
        });

        panSecundarioRutina.setBackground(new java.awt.Color(204, 255, 204));
        panSecundarioRutina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registra la nueva rutina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblIdRutina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdRutina.setText("Id:");

        lblNumeroRutina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumeroRutina.setText("Numero:");

        lblNombreRutina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreRutina.setText("Nombre de la rutina:");

        lblTipoRutina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoRutina.setText("Tipo:");

        lblRepeticionesRutina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRepeticionesRutina.setText("Repeticiones:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSecundarioRutinaLayout = new javax.swing.GroupLayout(panSecundarioRutina);
        panSecundarioRutina.setLayout(panSecundarioRutinaLayout);
        panSecundarioRutinaLayout.setHorizontalGroup(
            panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSecundarioRutinaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNombreRutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumeroRutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTipoRutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRepeticionesRutina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIdRutina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumeroRutina)
                    .addComponent(txtIdRutina)
                    .addComponent(txtNombreRutina)
                    .addComponent(txtTipoRutina)
                    .addComponent(txtRepeticionesRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(panSecundarioRutinaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        panSecundarioRutinaLayout.setVerticalGroup(
            panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSecundarioRutinaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdRutina)
                    .addComponent(txtIdRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroRutina))
                .addGap(29, 29, 29)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreRutina))
                .addGap(26, 26, 26)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoRutina))
                .addGap(36, 36, 36)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepeticionesRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRepeticionesRutina))
                .addGap(32, 32, 32)
                .addGroup(panSecundarioRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lblSeleccionaRutina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSeleccionaRutina.setText("Selecciona el tipo de rutina que quieras:");

        cboPartesCuerpo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboPartesCuerpo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Basica", "Intermedia", "Avanzada", "Hombros", "Biceps", "Triceps", "Gluteos", "Abdomen", "Antebrazos", "Pecho", "Espalda", "Pierna" }));
        cboPartesCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPartesCuerpoActionPerformed(evt);
            }
        });

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listo.png"))); // NOI18N
        jButton3.setText("Revisar actualizaciones");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrarrutina.png"))); // NOI18N

        javax.swing.GroupLayout panPrincipañLayout = new javax.swing.GroupLayout(panPrincipañ);
        panPrincipañ.setLayout(panPrincipañLayout);
        panPrincipañLayout.setHorizontalGroup(
            panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipañLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipañLayout.createSequentialGroup()
                        .addGroup(panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panPrincipañLayout.createSequentialGroup()
                                .addComponent(panSecundarioRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(panPrincipañLayout.createSequentialGroup()
                                .addComponent(lblSeleccionaRutina)
                                .addGap(28, 28, 28)
                                .addComponent(cboPartesCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(panPrincipañLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(bnRegresarMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(103, 103, 103))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipañLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipañLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(353, 353, 353))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipañLayout.createSequentialGroup()
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))))
        );
        panPrincipañLayout.setVerticalGroup(
            panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipañLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addGroup(panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionaRutina)
                    .addComponent(cboPartesCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipañLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panSecundarioRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPrincipañLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panPrincipañLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnRegresarMenu)
                    .addComponent(jButton3))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipañ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipañ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnRegresarMenuActionPerformed
        MenuAdmin ventanaAdministrador = new MenuAdmin();
        ventanaAdministrador.setVisible(true);
        this.hide();
    }//GEN-LAST:event_bnRegresarMenuActionPerformed

    private void cboPartesCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPartesCuerpoActionPerformed
        String mensaje = "La parte del cuerpo a ejercitar es ";
        mensaje= mensaje+cboPartesCuerpo.getSelectedItem().toString();
        lblResultado.setText(mensaje);
    }//GEN-LAST:event_cboPartesCuerpoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     conectarBase();
          //objeto libro toma metodo set de acceso a el dato y se parsea o convierte de objeto a primitivo.
        objRutina.setId(Integer.parseInt(txtIdRutina.getText()));
        objRutina.setNumRutina(Integer.parseInt(txtNumeroRutina.getText()));
        objRutina.setNombreRutina(txtNombreRutina.getText());
        objRutina.setTipo(txtTipoRutina.getText());
        objRutina.setRepeticiones(txtRepeticionesRutina.getText());

        //variable Objeto procesa instrucciones SQL para un INSERT.
        String altaRepeticiones = "INSERT INTO rutina (`ID`,`numRutina`,`nombreRutina`,`tipo`,`repeticiones`) VALUES ('"+objRutina.getId()+"','"+objRutina.getNumRutina()+"','"+objRutina.getNombreRutina()+"','"+objRutina.getTipo()+"','"+objRutina.getRepeticiones()+"')";

        //ejecutar con estructura de control de tratamiento de errores try-catch
        try {
            stmt.executeUpdate(altaRepeticiones);
            JOptionPane.showMessageDialog(null, "Registro Exitoso\n Rutina \n\n "+objRutina.getNumRutina());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error 3 de BD para Alta: \n\n" + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.txtIdRutina.setText("");
            this.txtNumeroRutina.setText("");
            this.txtNombreRutina.setText(null);
            this.txtTipoRutina.setText(null);
            this.txtRepeticionesRutina.setText(null);

            this.txtIdRutina.requestFocus();//posiciona cursor  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          ConsultaRutina ventanaConsulta = new ConsultaRutina();
                 ventanaConsulta.setVisible(true);
                    this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroRutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroRutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroRutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroRutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroRutina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnRegresarMenu;
    private javax.swing.JComboBox<String> cboPartesCuerpo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIdRutina;
    private javax.swing.JLabel lblNombreRutina;
    private javax.swing.JLabel lblNumeroRutina;
    private javax.swing.JLabel lblRepeticionesRutina;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSeleccionaRutina;
    private javax.swing.JLabel lblTipoRutina;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panPrincipañ;
    private javax.swing.JPanel panSecundarioRutina;
    private javax.swing.JTextField txtIdRutina;
    private javax.swing.JTextField txtNombreRutina;
    private javax.swing.JTextField txtNumeroRutina;
    private javax.swing.JTextField txtRepeticionesRutina;
    private javax.swing.JTextField txtTipoRutina;
    // End of variables declaration//GEN-END:variables
}
